### PR TITLE
Add support for properties files

### LINKED ISSUE #14: Allow vars to be specified via a prop file?
Looks like OTEL has an undocumented support for this: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/config/ConfigInitializer.java#L26

Precedence goes system properties >> env vars >> prop file

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
## Which problem is this PR solving?
Adds support for providing configuration via a properties file. Also sets the otel system variable to the same path if one has not been set.

- Closes #14

NOTE: There are not tests for this yet, it probably makes sense to use a smoke test as this is related to setting system properties & env vars

## Short description of the changes
- Updates EnvironmentConfiguration to look for `honeycomb.config.file` system property then `HONEYCOMB_CONFIG_FILE` environment variable as properties file path
- If a path is found, loads the file into an instance of `Properties`
- Update `readVariable` to check the properties file, then system properties and then environment variables
- Sets `otel.javaagent.configuration-file` system property, if it's not already set, so OTel java agent will try to read from the same file

### CODE REVIEW

**Comment by vreynolds** [comment]
Did upstream change their precedence? Last time I saw that it was: system properties >> env vars >> prop file

**Comment by MikeGoldsmith** [comment]
Ah, yeah - I misread that list and had it in reverse order 😁

**Review by vreynolds — APPROVED** [review]
🎈🎈🎈 We'll need to update docs as well

**Comment by MikeGoldsmith** [comment]
I have a docs [PR open](https://github.com/honeycombio/docs/pull/1045) already that is I linked it in the issue 😄

**Pull request merged**
