### PR TITLE
Update link

### PR DESCRIPTION
**Pull request by jessitron**
Instead of going to an old draft doc, how about the current doc on the real site?

## Which problem is this PR solving?

I'm trying to get this to work and those old docs are another source of confusion

## Short description of the changes

-

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
I think CI is out for lunch.

**Comment by jessitron** [comment]
it is opened and re-opened.

I think there might be another reference to the same link in the README, that also needs updated.

And we should remove the temp docs eh?

**Comment by MikeGoldsmith** [comment]
CI wasn't configured to build for forked builds. I've enabled that now and it's running.

**Comment by MikeGoldsmith** [comment]
I updated the other link too.

**Review by MikeGoldsmith — APPROVED** [review]

**Pull request merged**
